insert into missive_field_all (field_name,process_type_id) values ('密级',1);
insert into missive_field_all (field_name,process_type_id) values ('签发人员',1);
insert into missive_field_all (field_name,process_type_id) values ('签发内容',1);
insert into missive_field_all (field_name,process_type_id) values ('公文种类',1);
insert into missive_field_all (field_name,process_type_id) values ('会签人员',1);
insert into missive_field_all (field_name,process_type_id) values ('会签内容',1);
insert into missive_field_all (field_name,process_type_id) values ('主办单位',1);
insert into missive_field_all (field_name,process_type_id) values ('主送人员',1);
insert into missive_field_all (field_name,process_type_id) values ('主送内容',1);
insert into missive_field_all (field_name,process_type_id) values ('抄报人员',1);
insert into missive_field_all (field_name,process_type_id) values ('抄报内容',1);
insert into missive_field_all (field_name,process_type_id) values ('拟稿人',1);
insert into missive_field_all (field_name,process_type_id) values ('电话',1);
insert into missive_field_all (field_name,process_type_id) values ('办公室复核',1);
insert into missive_field_all (field_name,process_type_id) values ('校对',1);
insert into missive_field_all (field_name,process_type_id) values ('处(室)领导核稿人员',1);
insert into missive_field_all (field_name,process_type_id) values ('处(室)领导核稿内容',1);
insert into missive_field_all (field_name,process_type_id) values ('抄送人员',1);
insert into missive_field_all (field_name,process_type_id) values ('抄送_Content',1);
insert into missive_field_all (field_name,process_type_id) values ('打印份数',1);
insert into missive_field_all (field_name,process_type_id) values ('标题',1);
insert into missive_field_all (field_name,process_type_id) values('收文日期',2);
insert into missive_field_all (field_name,process_type_id) values('收文号',2);
insert into missive_field_all (field_name,process_type_id) values('文件字号',2);
insert into missive_field_all (field_name,process_type_id) values('____份',2);
insert into missive_field_all (field_name,process_type_id) values('紧急程度',2);
insert into missive_field_all (field_name,process_type_id) values('密级',2);
insert into missive_field_all (field_name,process_type_id) values('办理时限',2);
insert into missive_field_all (field_name,process_type_id) values('来文摘要',2);
insert into missive_field_all (field_name,process_type_id) values('办公室拟办',2);
insert into missive_field_all (field_name,process_type_id) values('办公室拟办_月',2);
insert into missive_field_all (field_name,process_type_id) values('办公室拟办_日',2);
insert into missive_field_all (field_name,process_type_id) values('领导批示',2);
insert into missive_field_all (field_name,process_type_id) values('阅办人签字',2);
insert into missive_field_all (field_name,process_type_id) values('承办情况',2);
insert into missive_field_all (field_name,process_type_id) values('承办人',2);
insert into missive_field_all (field_name,process_type_id) values('承办月',2);
insert into missive_field_all (field_name,process_type_id) values('承办日',2);
insert into missive_field_all (field_name,process_type_id) values('请示件',3);
insert into missive_field_all (field_name,process_type_id) values('报告件',3);
insert into missive_field_all (field_name,process_type_id) values('加急',3);
insert into missive_field_all (field_name,process_type_id) values('急',3);
insert into missive_field_all (field_name,process_type_id) values('普通',3);
insert into missive_field_all (field_name,process_type_id) values('主办单位',3);
insert into missive_field_all (field_name,process_type_id) values('拟稿人',3);
insert into missive_field_all (field_name,process_type_id) values('拟稿日期',3);
insert into missive_field_all (field_name,process_type_id) values('联系电话',3);
insert into missive_field_all (field_name,process_type_id) values('处室意见',3);
insert into missive_field_all (field_name,process_type_id) values('处室意见_月',3);
insert into missive_field_all (field_name,process_type_id) values('处室意见_日',3);
insert into missive_field_all (field_name,process_type_id) values('办公室意见',3);
insert into missive_field_all (field_name,process_type_id) values('办公室意见_月',3);
insert into missive_field_all (field_name,process_type_id) values('办公室意见_日',3);
insert into missive_field_all (field_name,process_type_id) values('会签部门意见',3);
insert into missive_field_all (field_name,process_type_id) values('领导批示',3);
insert into missive_field_all (field_name,process_type_id) values('领导批示_月',3);
insert into missive_field_all (field_name,process_type_id) values('领导批示_日',3);
insert into missive_field_all (field_name,process_type_id) values('标题',3);


